apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: mendikup-dev
spec:
  selector:
    matchLabels:
      app: kafka
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - image: bitnami/kafka:3.7
        name: kafka
        imagePullPolicy: Always
        env:
          - name: KAFKA_CFG_NODE_ID
            value: "1"
          - name: KAFKA_CFG_PROCESS_ROLES
            value: broker,controller
          - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
            value: 1@kafka:9093
          - name: KAFKA_CFG_LISTENERS
            value: PLAINTEXT://:9092,CONTROLLER://:9093
          - name: KAFKA_CFG_ADVERTISED_LISTENERS
            value: PLAINTEXT://kafka:9092
          - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
            value: CONTROLLER
          - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
            value: "true"
        ports:
        - containerPort: 9092
          name: kafka