apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-retrieval
  namespace: avigoldshtein-dev
spec:
  selector:
    matchLabels:
      app: data-retrieval
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: data-retrieval
    spec:
      containers:
      - image: avigoldshtein/data-retrieval:latest
        name: data-retrieval
        imagePullPolicy: Always
        env:
          - name: KAFKA_BOOTSTRAP
          - value: kafka:9092
          - name: MONGO_URI
            value: mongodb://mongo:27017 # MongoDB connection string
          - name: MONGO_DB
            value: mydb # MongoDB database
          - name: ANTISEMITIC_COLLECTION
            value: tweets_antisemitic # collection for antisemitic tweets
          - name: NOT_ANTISEMITIC_COLLECTION
            value: tweets_not_antisemitic # collection for non-antisemitic tweets
        ports:
        - containerPort: 8004
          name: data-retrieval
