apiVersion: apps/v1
kind: Deployment
metadata:
  name: persister
  namespace: avigoldshtein-dev
spec:
  selector:
    matchLabels:
      app: persister
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: persister
    spec:
      containers:
      - image: avigoldshtein/persister:latest
        name: persister
        imagePullPolicy: Always
        env:
          - name: KAFKA_BOOTSTRAP
            value: kafka:9092
          - name: MONGO_URI
            value: mongodb://mongo:27017
          - name: MONGO_DB
            value: mydb # MongoDB database
          - name: ENRICHED_PREPROCESSED_TWEETS_ANTISEMITIC
            value: enriched_preprocessed_tweets_antisemitic # topic for enriched antisemitic tweets
          - name: ENRICHED_PREPROCESSED_TWEETS_NOT_ANTISEMITIC
            value: enriched_preprocessed_tweets_not_antisemitic # topic for enriched non-antisemitic tweets
          - name: ANTISEMITIC_COLLECTION
            value: tweets_antisemitic # collection for antisemitic tweets
          - name: NOT_ANTISEMITIC_COLLECTION
            value: tweets_not_antisemitic # collection for non-antisemitic tweets
